services:
  persons:
    image: persons
    build:
      context: .
      dockerfile: PersonService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PersonServicePostgresContext=Host=postgres;Database=persons;Username=postgres;Password=123
    networks:
      - yacrm-network
  postgres:
    image: postgres:16-alpine
    container_name: loadtest-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - yacrm-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d persons" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  yacrm-network:
    driver: bridge